### ISSUE TITLE
Release on General registry

### ISSUE THREAD

**Issue by TransGirlCodes** [BioJulia/MicrobiomePlots.jl#15]
I've transferred Microbiome to the General registry. The BioJuliaRegistry has a version 0.2.0 but I can't see the commit used to trigger the bot or a 0.2 tag?

**Comment by kescobo** [comment]
I think maybe I should deprecate this package in favor of the recipes functionality that's going to be coming soon with Plots and Makie. I'll just put the recipes in Microbiome directly. So let's not transfer this.
